# Generated by Django 4.2.2 on 2023-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to='notes.registereduser'),
        ),
    ]
