# Generated by Django 4.2.2 on 2023-06-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_shared_with'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
